Repository Azure/azure-sdk-for-c, pull requests merged in 2020-09, with the labels that each got.

#1187 Update link to point to cmake options.
  README.md
  sdk/docs/platform/README.md
Labels: Docs

#1179 moving Doxyfile to /doc
  CONTRIBUTING.md
  doc/Doxyfile
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: Docs

#1173 Update PnP Sample
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
Labels: Client, Iot

#1174 Fix AV in logging when classification array isn't valid and add tests.
  sdk/inc/azure/core/az_log.h
  sdk/src/azure/core/az_log.c
  sdk/tests/core/test_az_logging.c
  sdk/tests/iot/common/test_az_iot_common.c
Labels: Azure.Core, bug

#1177 Sync eng/common directory with azure-sdk-tools for PR 935
  eng/common/scripts/SemVer.ps1
Labels: EngSys

#1151 Sync eng/common directory with azure-sdk-tools for PR 916
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys

#1154 Sync eng/common directory with azure-sdk-tools for PR 930
  eng/common/README.md
Labels: EngSys

#1196 Fix compiler warning unicode chars
  sdk/src/azure/core/az_http_header_validation_private.h
Labels: Azure.Core

#1202 update iot sample readme
  sdk/samples/iot/README.md
Labels: Iot

#1200 Sync eng/common directory with azure-sdk-tools for PR 946
  eng/common/Update-Change-Log.ps1
Labels: EngSys

#1181 Do not use a shared static scratch buffer for JSON token parsing. Instead use stack space.
  sdk/src/azure/core/az_json_private.h
  sdk/src/azure/core/az_json_token.c
  sdk/src/azure/core/az_json_writer.c
  sdk/src/azure/core/az_span.c
  sdk/src/azure/core/az_span_private.h
Labels: Azure.Core

#1135 Update doxygen version to 1.8.20 to get some recent bug fixes.
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/tests/core/test_az_http.c
Labels: Docs, infrastructure

#1204 Sync eng/common directory with azure-sdk-tools for PR 955
  eng/common/Update-Change-Log.ps1
Labels: EngSys

#1134 Add ARM compile to matrix
  cmake-modules/gcc-arm-toolchain.cmake
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: infrastructure

#1186 Publish artifacts for docs.ms
  doc/Doxyfile
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/New-DocsMsArtifact.ps1
Labels: Docs

#1149 Sync eng/common directory with azure-sdk-tools for PR 926
  eng/common/Update-Change-Log.ps1
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys

#1205 Clean up IoT header file doxygen
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
  sdk/samples/iot/pnp/pnp_protocol.h
Labels: Iot

#1161 Sync eng/common directory with azure-sdk-tools for PR 823
  eng/common/pipelines/templates/steps/verify-changelog.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
  eng/common/scripts/common.ps1
Labels: EngSys

#1212 Update Language Settings File
  eng/scripts/Language-Settings.ps1
Labels: EngSys

#1216 Sync eng/common directory with azure-sdk-tools repository
  eng/common/Update-Change-Log.ps1
Labels: EngSys

#1199 Add script that validates all files in the repo contain ASCII-only bytes and no UTF-8 BOM.
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: infrastructure

#1203 PR #1194 follow up
  CHANGELOG.md
  sdk/inc/azure/core/az_http_transport.h
  sdk/inc/azure/core/internal/az_http_internal.h
Labels: Azure.Core

#1207 AZ_ERROR_DEPENDENCY_NOT_PROVIDED
  README.md
  sdk/docs/core/README.md
  sdk/docs/platform/README.md
  sdk/inc/azure/core/az_result.h
  sdk/samples/storage/blobs/src/blobs_client_example.c
  sdk/src/azure/platform/az_nohttp.c
Labels: Azure.Core, Design

#1209 Use gcc-5
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys

#1208 Only create map files if cmake is 3.13 or greater
  CMakeLists.txt
  cmake-modules/create_map_file.cmake
  sdk/samples/storage/blobs/CMakeLists.txt
  sdk/tests/core/CMakeLists.txt
  sdk/tests/iot/common/CMakeLists.txt
  sdk/tests/iot/hub/CMakeLists.txt
  sdk/tests/iot/provisioning/CMakeLists.txt
  sdk/tests/storage/blobs/CMakeLists.txt
Labels: EngSys

#1219 Update README.md with more specific details about az_nohttp.
  README.md
Labels: Docs

#1221 Rename AZ_ERROR_INSUFFICIENT_SPAN_SIZE to be more generic: AZ_ERROR_NOT_ENOUGH_SPACE
  CHANGELOG.md
  sdk/inc/azure/core/az_http_transport.h
  sdk/inc/azure/core/az_json.h
  sdk/inc/azure/core/az_result.h
  sdk/inc/azure/core/az_span.h
  sdk/inc/azure/core/internal/az_http_internal.h
  sdk/inc/azure/core/internal/az_result_internal.h
  sdk/inc/azure/core/internal/az_span_internal.h
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/src/azure/core/az_json_token.c
  sdk/src/azure/core/az_json_writer.c
  sdk/src/azure/core/az_span.c
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/tests/core/test_az_http.c
  sdk/tests/core/test_az_json.c
  sdk/tests/core/test_az_span.c
  sdk/tests/core/test_az_url_encode.c
  sdk/tests/iot/common/test_az_iot_common.c
  sdk/tests/iot/hub/test_az_iot_hub_client.c
  sdk/tests/iot/hub/test_az_iot_hub_client_methods.c
  sdk/tests/iot/hub/test_az_iot_hub_client_sas.c
  sdk/tests/iot/hub/test_az_iot_hub_client_telemetry.c
  sdk/tests/iot/hub/test_az_iot_hub_client_twin.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_sas.c
Labels: Azure.Core, Design

#1214 update doxygen from feedback
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/samples/iot/paho_iot_hub_twin_sample.c
Labels: Docs, Iot

#1223 Make the build pipeline that creates a directory more resilient if the build directory already exists.
  .gitignore
  eng/pipelines/templates/steps/cmake-build.yml
Labels: infrastructure

#1224 Avoid using !az_result_succeeded or failed, and instead use the appropriate function.
  sdk/inc/azure/core/az_span.h
  sdk/src/azure/core/az_http_policy_retry.c
  sdk/src/azure/core/az_json_writer.c
Labels: Azure.Core

#1218 Sync eng/common directory with azure-sdk-tools for PR 969
  eng/common/README.md
Labels: EngSys

#1240 Do not validate that the version contains beta, since C uses preview for the first release.
  eng/scripts/Update-SdkVersion.ps1
Labels: EngSys

#1239 Add parameters to function
  eng/scripts/Language-Settings.ps1
Labels: EngSys

#1232 add further info for device id encoding
  sdk/inc/azure/iot/az_iot_hub_client.h
Labels: Docs, Iot

#1210 PnP Component Sample Update
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_device_info_component.h
  sdk/samples/iot/pnp/pnp_mqtt_message.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
Labels: Client, Iot

#1246 update provisioning field name to registration state
  CHANGELOG.md
  sdk/docs/iot/mqtt_state_machine.md
  sdk/docs/iot/resources/iot_provisioning_flow.puml
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/src/azure/iot/az_iot_common.c
  sdk/src/azure/iot/az_iot_hub_client_twin.c
  sdk/src/azure/iot/az_iot_provisioning_client.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
Labels: Iot

#1225 Small Dox correction: verbatim semver.org
  sdk/inc/azure/core/az_http_transport.h
  sdk/inc/azure/core/az_version.h
Labels: Azure.Core, Docs

#1245 update logging logic for IoT
  sdk/src/azure/iot/az_iot_common.c
  sdk/src/azure/iot/az_iot_hub_client_c2d.c
  sdk/src/azure/iot/az_iot_hub_client_methods.c
  sdk/tests/iot/common/test_az_iot_common.c
  sdk/tests/iot/hub/test_az_iot_hub_client_c2d.c
  sdk/tests/iot/hub/test_az_iot_hub_client_methods.c
  sdk/tests/iot/hub/test_az_iot_hub_client_sas.c
  sdk/tests/iot/hub/test_az_iot_hub_client_twin.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_sas.c
Labels: Iot

#1248 Update return code structure for all samples.
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_mqtt_message.c
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_thermostat_component.c
Labels: Client, Iot

#1217 Use vcpkg cache correctly
  .gitignore
  README.md
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/pipelines/templates/steps/vcpkg.yml
  eng/scripts/vcpkg.ps1
  eng/vcpkg-commit.txt
Labels: EngSys

#1253 update iot test names
  sdk/tests/iot/hub/test_az_iot_hub_client.c
  sdk/tests/iot/hub/test_az_iot_hub_client_twin.c
Labels: Iot

#1250 Refactor az_iot_provisioning_client_register_response to change operation_status to enum vaule
  CHANGELOG.md
  sdk/inc/azure/iot/az_iot_provisioning_client.h
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/src/azure/iot/az_iot_provisioning_client.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
Labels: Iot

#1254 Enable the master link replacement feature for c
  eng/pipelines/templates/stages/archetype-c-release.yml
Labels: EngSys

#1211 Sync eng/common directory with azure-sdk-tools for PR 965
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: EngSys

#1234 Sync eng/common directory with azure-sdk-tools for PR 973
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys

#1264 update az_iot_hub_client_twin_response_type enum values
  CHANGELOG.md
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/src/azure/iot/az_iot_hub_client_twin.c
  sdk/tests/iot/hub/test_az_iot_hub_client_twin.c
Labels: Iot

#1267 Updates for cmake modules
  CMakeLists.txt
  cmake-modules/AddTestCMocka.cmake
  cmake-modules/CheckAndIncludeCodeCov.cmake
  cmake-modules/CodeCoverage.cmake
  cmake-modules/CreateCodeCoverageTargets.cmake
  cmake-modules/create_map_file.cmake
  cmake-modules/gcc-arm-toolchain.cmake
Labels: infrastructure

#1266 Documentation Samples - README.md, Windows and Linux how-to
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
  sdk/samples/iot/generate_certificate.ps1
Labels: Client, Docs, Iot

#1268 Sync eng/common directory with azure-sdk-tools for PR 999
  eng/common/scripts/update-docs-metadata.ps1
Labels: EngSys

#1271 Update how_to_iot_hub_esp8266_nodemcu.md with latest env setup info
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
Labels: Docs, Iot

#1269 Sync eng/common directory with azure-sdk-tools for PR 1000
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/create-tags-and-git-release.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/replace-relative-links.yml
Labels: EngSys

#1213 Adding Notice for code coverage cmake module
  NOTICE.txt
  cgmanifest.json
Labels: infrastructure

#1272 windows sample readme update
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Iot

#1238 Sync eng/common directory with azure-sdk-tools for PR 974
  eng/common/scripts/common.ps1
  eng/common/scripts/logging.ps1
Labels: EngSys

#1236 Sync eng/common directory with azure-sdk-tools for PR 895
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys

#1270 updates on samples verbiage
  sdk/docs/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Docs, Iot

#1191 Remove validating precondition in 'az_log_set_classifications'
  sdk/inc/azure/core/az_log.h
  sdk/src/azure/core/az_log.c
Labels: Azure.Core, Design

#1243 Clean-up the .clang-format file and run clang-format on all .c and .h files in the repo.
  .clang-format
  sdk/inc/azure/core/az_context.h
  sdk/samples/iot/aziot_esp8266/iot_configs.h
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/src/azure/core/az_http_policy_logging.c
  sdk/tests/iot/common/main.c
  sdk/tests/iot/provisioning/main.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
Labels: auto-merge, infrastructure

#1279 Make the Linux_x64_with_unit_test CI leg more descriptive.
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys, auto-merge

#1256 Make Platform functions to return az_result
  CHANGELOG.md
  README.md
  sdk/docs/core/README.md
  sdk/docs/platform/README.md
  sdk/inc/azure/core/az_http_transport.h
  sdk/inc/azure/core/az_platform.h
  sdk/src/azure/core/az_http_policy_logging.c
  sdk/src/azure/core/az_http_policy_retry.c
  sdk/src/azure/platform/az_curl.c
  sdk/src/azure/platform/az_nohttp.c
  sdk/src/azure/platform/az_noplatform.c
  sdk/src/azure/platform/az_posix.c
  sdk/src/azure/platform/az_win32.c
  sdk/tests/core/CMakeLists.txt
  sdk/tests/core/test_az_policy.c
Labels: Azure.Core

#1278 Add script that validates all *.c and *.h files in the repo have been properly formatted according to .clang-format
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys, auto-merge

#1285 Fix spacing on az_posix to satisfy clang format.
  sdk/src/azure/platform/az_posix.c
Labels: Azure.Core, auto-merge

#1282 update Cmake options references in Readme
  CONTRIBUTING.md
  README.md
Labels: Docs

#1301 GA: Final samples README.md, how to guide for Linux, how to guide for Windows
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Client, Docs, Iot

#1296 Replaced relative link with absolute links and remove locale
  CONTRIBUTING.md
  README.md
  SECURITY.md
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/docs/core/README.md
  sdk/docs/iot/README.md
  sdk/docs/iot/hub.md
  sdk/docs/iot/mqtt_state_machine.md
  sdk/docs/iot/provisioning.md
  sdk/docs/platform/README.md
  sdk/docs/storage/README.md
  sdk/samples/core/README.md
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
  sdk/samples/storage/blobs/README.md
Labels: EngSys

#1294 mention min doxygen version
  CONTRIBUTING.md
Labels: Docs

#1306 delete generate_certificate.ps1
  sdk/samples/iot/generate_certificate.ps1
Labels: Client, Docs, Iot

#1293 adding platform info for live tests generation
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
Labels: EngSys

#1299 Cmake module for using cmake fetchcontent
  README.md
  cmake-modules/AddAzureSDKforC.cmake
Labels: EngSys

#1304 Reorder fields within az_json_reader for better packing and to avoid IAR warning for int assignment to an enum.
  sdk/inc/azure/core/az_json.h
Labels: Azure.Core

#1312 Make sure no struct contains an enum as the first field to avoid IAR warning on { 0 } init.
  sdk/inc/azure/core/az_http.h
  sdk/inc/azure/core/internal/az_http_internal.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
Labels: Azure.Core, Client, Iot, bug

#1297 Move IoT az_result and log classification enum values to separate headers without introducing new typedefs
  CHANGELOG.md
  sdk/inc/azure/core/az_log.h
  sdk/inc/azure/core/az_result.h
  sdk/inc/azure/iot/az_iot_common.h
  sdk/tests/core/test_az_logging.c
Labels: Design

#1308 Docs: More details about az_log_set_classifications()
  sdk/docs/core/README.md
  sdk/inc/azure/core/az_log.h
  sdk/samples/storage/blobs/src/blobs_client_example.c
Labels: Azure.Core, Docs

#1305 Update and fix for esp8266 how to sample guide
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Client, Docs, Iot

#1287 Update read me about samples
  README.md
Labels: Azure.Core, Docs

#1313 update API version
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/tests/iot/hub/test_az_iot_hub_client.c
Labels: Iot

#1252 Remove az_result return type for custom sample functions
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_device_info_component.h
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
Labels: Client, Iot

#1258 Add release build configs into CI matrix
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys

#1323 Sample doc edits
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Client, Docs, Iot

#1324 Update CI build names
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: auto-merge

#1328 Update notice.txt file and format the cgmanifest.json file.
  NOTICE.txt
  cgmanifest.json
Labels: EngSys

#1331 Turn DevelopmentDependency to false to test out behavior.
  cgmanifest.json
Labels: EngSys

#1333 Make az_log_set_classifications internal.
  CHANGELOG.md
  sdk/docs/core/README.md
  sdk/inc/azure/core/az_log.h
  sdk/inc/azure/core/internal/az_log_internal.h
  sdk/samples/storage/blobs/src/blobs_client_example.c
  sdk/src/azure/core/az_log.c
  sdk/tests/core/test_az_logging.c
  sdk/tests/iot/common/test_az_iot_common.c
  sdk/tests/iot/hub/test_az_iot_hub_client_c2d.c
  sdk/tests/iot/hub/test_az_iot_hub_client_methods.c
  sdk/tests/iot/hub/test_az_iot_hub_client_sas.c
  sdk/tests/iot/hub/test_az_iot_hub_client_twin.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_sas.c
Labels: Azure.Core, Design

#1315 Storage Blob Upload
  .github/CODEOWNERS
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  eng/docs/index/Generate-DocIndex.ps1
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  samples/README.md
  sdk/docs/storage/LICENSE
  sdk/docs/storage/README.md
  sdk/inc/azure/storage/az_storage_blobs.h
  sdk/samples/storage/blobs/CMakeLists.txt
  sdk/samples/storage/blobs/README.md
  sdk/samples/storage/blobs/src/blobs_client_example.c
  sdk/samples/storage/blobs/test-resources-post.ps1
  sdk/samples/storage/blobs/test-resources.json
  sdk/src/azure/storage/CMakeLists.txt
  sdk/src/azure/storage/az_storage_blobs_blob_client.c
  sdk/tests/storage/blobs/CMakeLists.txt
  sdk/tests/storage/blobs/az_storage_blobs_unit_tests.c
  sdk/tests/storage/blobs/main.c
Labels: Design, Storage

#1335 Revert "Turn DevelopmentDependency to false to test out behavior.
  cgmanifest.json
Labels: EngSys

#1334 Add Component Governance task to CI yaml.
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys

#1337 Update cgmanifest to include vcpkg dependencies and linux tools we use in CI.
  cgmanifest.json
Labels: EngSys

#1340 Remove end of array sentinel for HTTP status codes.
  CHANGELOG.md
  sdk/inc/azure/core/az_http.h
  sdk/src/azure/core/az_http_policy_retry.c
Labels: Azure.Core, Design

#1336 Rev version
  sdk/inc/azure/core/az_version.h
Labels: Azure.Core, Client

#1316 Sync eng/common directory with azure-sdk-tools for PR 1022
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1344 Use return instead of retval for boolean values in az_result docs.
  sdk/inc/azure/core/az_result.h
Labels: Azure.Core, Docs

#1355 Update doxygen for provisioning and hub
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
Labels: Docs, Iot

#1342 Add 3rd party licenses for VCPKG dependencies to NOTICE.txt file.
  NOTICE.txt
Labels: EngSys

#1343 Update internal names of facilities to include `_CORE` and `_IOT` infix to act as grouping.
  sdk/inc/azure/core/az_log.h
  sdk/inc/azure/core/az_result.h
  sdk/inc/azure/iot/az_iot_common.h
Labels: Azure.Core

#1314 Add precondition check to validate clients are initialized before passed in to public APIs.
  sdk/src/azure/iot/az_iot_hub_client_c2d.c
  sdk/src/azure/iot/az_iot_hub_client_methods.c
  sdk/src/azure/iot/az_iot_hub_client_twin.c
  sdk/src/azure/iot/az_iot_provisioning_client.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
Labels: Iot

#1345 Update doc format of #define macros in iot_common so they render better in VS and doxygen.
  sdk/inc/azure/iot/az_iot_common.h
Labels: Docs, Iot, auto-merge

#1289 Add high-level az_core.h and az_iot.h files for simpler include experience for customers.
  sdk/inc/azure/az_core.h
  sdk/inc/azure/az_iot.h
Labels: Design, auto-merge

#1261 Places where we have const* arguments in source, optionally mark the value as const as well.
  sdk/src/azure/core/az_context.c
  sdk/src/azure/core/az_http_policy_logging.c
  sdk/src/azure/core/az_http_request.c
  sdk/src/azure/core/az_http_response.c
  sdk/src/azure/core/az_json_reader.c
  sdk/src/azure/core/az_json_token.c
  sdk/src/azure/core/az_json_writer.c
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/src/azure/iot/az_iot_hub_client_c2d.c
  sdk/src/azure/iot/az_iot_hub_client_methods.c
  sdk/src/azure/iot/az_iot_hub_client_sas.c
  sdk/src/azure/iot/az_iot_hub_client_telemetry.c
  sdk/src/azure/iot/az_iot_hub_client_twin.c
  sdk/src/azure/iot/az_iot_provisioning_client.c
  sdk/src/azure/iot/az_iot_provisioning_client_sas.c
  sdk/src/azure/platform/az_curl.c
  sdk/src/azure/platform/az_nohttp.c
Labels: auto-merge

#1259 Sync eng/common directory with azure-sdk-tools for PR 989
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
  eng/common/scripts/get-pr-creator.ps1
Labels: Central-EngSys, EngSys

#1317 Use a should_write callback method to let the caller decide what should and shouldn't get logged.
  CHANGELOG.md
  sdk/docs/core/README.md
  sdk/inc/azure/core/az_log.h
  sdk/inc/azure/core/internal/az_log_internal.h
  sdk/src/azure/core/az_log.c
  sdk/tests/core/test_az_logging.c
  sdk/tests/iot/common/test_az_iot_common.c
  sdk/tests/iot/hub/test_az_iot_hub_client_c2d.c
  sdk/tests/iot/hub/test_az_iot_hub_client_methods.c
  sdk/tests/iot/hub/test_az_iot_hub_client_sas.c
  sdk/tests/iot/hub/test_az_iot_hub_client_twin.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_parser.c
  sdk/tests/iot/provisioning/test_az_iot_provisioning_client_sas.c
Labels: Azure.Core, Design

#1356 Sync eng/common directory with azure-sdk-tools for PR 1041
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
  eng/common/scripts/get-pr-creator.ps1
Labels: EngSys

#1354 For vcpkg dependencies, update the component type to git, within cgmanifest.
  cgmanifest.json
Labels: EngSys, auto-merge

#1358 Fix typo in notices
  NOTICE.txt
Labels: auto-merge

#1360 Add a .gitattributes file and normalize line endings.
  .gitattributes
  LICENSE
  README.md
  sdk/docs/iot/README.md
  sdk/docs/iot/mqtt_state_machine.md
  sdk/docs/iot/resources/iot_hub_flow.puml
  sdk/docs/iot/resources/iot_provisioning_flow.puml
  sdk/docs/iot/resources/iot_retry_flow.puml
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
Labels: EngSys, auto-merge

#1310 Add Plug and Play API's
  CMakeLists.txt
  sdk/docs/iot/README.md
  sdk/docs/iot/pnp.md
  sdk/inc/azure/iot/az_iot_pnp_client.h
  sdk/samples/iot/CMakeLists.txt
  sdk/samples/iot/README.md
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
  sdk/src/azure/iot/CMakeLists.txt
  sdk/src/azure/iot/az_iot_pnp_client.c
  sdk/src/azure/iot/az_iot_pnp_client_commands.c
  sdk/src/azure/iot/az_iot_pnp_client_sas.c
  sdk/src/azure/iot/az_iot_pnp_client_telemetry.c
  sdk/src/azure/iot/az_iot_pnp_client_twin.c
  sdk/tests/iot/pnp/CMakeLists.txt
  sdk/tests/iot/pnp/main.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client.h
  sdk/tests/iot/pnp/test_az_iot_pnp_client_commands.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_sas.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_telemetry.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_twin.c
Labels: Iot

#1325 Sync eng/common directory with azure-sdk-tools for PR 1029
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#1242 Remove trailing white space and insert final new lines.
  .editorconfig
  .vscode-config/launch.json
  .vscode-config/tasks.json
  CMakeSettings.json
  NOTICE.txt
  README.md
  SECURITY.md
  cmake-modules/AddTestCMocka.cmake
  cmake-modules/CreateCodeCoverageTargets.cmake
  eng/cmake/global_compile_options.txt
  eng/docs/api/assets/DoxygenLayout.xml
  eng/docs/api/assets/style.css
  eng/docs/api/generate_docs.py
  eng/docs/index/Generate-DocIndex.ps1
  eng/docs/index/assets/docfx.json
  eng/docs/index/assets/toc.yml
  eng/docs/index/docfx.json
  eng/docs/index/templates/matthews/styles/main.css
  eng/docs/index/templates/matthews/styles/main.js
  eng/pipelines/doc-index.yml
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/pipelines/templates/stages/archetype-c-release.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  eng/pipelines/templates/steps/cmake-build.yml
  eng/scripts/Get-SdkVersion.ps1
  eng/scripts/Language-Settings.ps1
  eng/scripts/vcpkg.ps1
  eng/vcpkg-commit.txt
  sdk/docs/iot/README.md
  sdk/docs/iot/resources/iot_hub_flow.puml
  sdk/docs/iot/resources/iot_provisioning_flow.puml
  sdk/docs/iot/resources/iot_retry_flow.puml
  sdk/samples/iot/aziot_esp8266/aziot_esp8266.ino
  sdk/samples/iot/x509_config.cfg
  sdk/src/azure/core/CMakeLists.txt
  sdk/src/azure/platform/CMakeLists.txt
  sdk/tests/core/CMakeLists.txt
  sdk/tests/iot/common/CMakeLists.txt
Labels: EngSys

#1362 Cgmanifest update: Remove transitive dependencies, mark paho as devdep, and simplify clang-format version.
  cgmanifest.json
Labels: EngSys, auto-merge

#1365 update az_iot_pnp_client_twin_get_next_component_property() API
  sdk/inc/azure/iot/az_iot_pnp_client.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
  sdk/src/azure/iot/az_iot_pnp_client_twin.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_twin.c
Labels: Iot

#1363 update property with status API
  sdk/inc/azure/iot/az_iot_pnp_client.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/src/azure/iot/az_iot_pnp_client_twin.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_twin.c
Labels: Iot

#1353 Update header includes in samples
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_device_info_component.h
  sdk/samples/iot/pnp/pnp_mqtt_message.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
Labels: Client, Iot

#1274 Change doxygen doc generation output folder
  .gitignore
  doc/Doxyfile
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/scripts/New-DocsMsArtifact.ps1
Labels: Docs

#1366 Adding link to cmake module
  README.md
Labels: Client, Docs

#1338 Fix libcmt/libcmtd.lib link warning
  cmake-modules/AddTestCMocka.cmake
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/samples/iot/CMakeLists.txt
  sdk/tests/iot/common/CMakeLists.txt
  sdk/tests/iot/hub/CMakeLists.txt
  sdk/tests/iot/provisioning/CMakeLists.txt
Labels: EngSys

#1369 update twin APIs to property
  sdk/inc/azure/iot/az_iot_pnp_client.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/src/azure/iot/CMakeLists.txt
  sdk/src/azure/iot/az_iot_pnp_client_property.c
  sdk/tests/iot/pnp/CMakeLists.txt
  sdk/tests/iot/pnp/main.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client.h
  sdk/tests/iot/pnp/test_az_iot_pnp_client_commands.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_property.c
Labels: Iot

#1377 Revert "avoid reading address from size 0 span (#1373)"
  cmake-modules/AddCmockaFunctions.cmake
  sdk/src/azure/core/az_http_response.c
Labels: Azure.Core

#1327 Sync eng/common directory with azure-sdk-tools for PR 1032
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
Labels: EngSys

#1379 avoid reading from size 0 span
  sdk/src/azure/core/az_http_response.c
  sdk/tests/core/test_az_http.c
Labels: Azure.Core, auto-merge

#1376 Sync eng/common directory with azure-sdk-tools for PR 1056
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys, bug

#1378 Sync eng/common directory with azure-sdk-tools for PR 1059
  eng/common/README.md
Labels: Central-EngSys, EngSys

#1382 Consume CMocka CMake module directly from CMocka repo
  CMakeLists.txt
  cmake-modules/AddCMockaTest.cmake
  sdk/tests/core/CMakeLists.txt
  sdk/tests/iot/common/CMakeLists.txt
  sdk/tests/iot/hub/CMakeLists.txt
  sdk/tests/iot/provisioning/CMakeLists.txt
Labels: auto-merge

#1374 Component sample update
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
Labels: Iot

#1384 Sync eng/common directory with azure-sdk-tools for PR 1061
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
  eng/common/scripts/logging.ps1
Labels: Central-EngSys, EngSys

#1385 update name of component sample
  sdk/samples/iot/CMakeLists.txt
  sdk/samples/iot/README.md
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_pnp_component_sample.c
Labels: Iot
