Repository Azure/azure-sdk-for-c, pull requests merged in 2020-02, with the labels that each got.

#335 Install the latest gcc in the mac build
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/transportPolicies/curl/src/az_curl.c
Labels: Engineering System

#344 Add security policy
  SECURITY.md
Labels: Client, documentation

#312 add doxyfile template, pipeline, and supporting artifacts
  eng/docs/Doxyfile.template
  eng/docs/assets/footer.html
  eng/docs/assets/header.html
  eng/docs/assets/style.css
  eng/docs/generate_docs.py
  eng/pipelines/docs.yml
Labels: Engineering System

#373 Create NOTICE.txt
  NOTICE.txt
Labels: documentation

#346 remove path constraints on ci triggers
  eng/pipelines/client.yml
Labels: Engineering System
