Repository Azure/azure-sdk-for-c, pull requests merged in 2020-10, with the labels that each got.

#1326 Sync eng/common directory with azure-sdk-tools for PR 1031
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
  eng/common/scripts/New-ReleaseAsset.ps1
Labels: Central-EngSys, EngSys

#1390 Add a notice for preview Plug and Play features
  sdk/docs/iot/README.md
Labels: Iot

#1397 Make it clearer that the SDK should be built only against a particular version of the dependencies.
  README.md
Labels: Docs

#1394 Fix Windows to use /MT when building static libraries.
  CMakeLists.txt
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys, auto-merge

#1396 Sample PnP description update
  sdk/docs/iot/README.md
Labels: Client, Docs, Iot

#1348 preview => release
  cmake-modules/AddAzureSDKforC.cmake
  sdk/docs/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
Labels: Docs, EngSys, Iot, auto-merge

#1347 Update mentions of preview to beta going forward for releases after 1.0.0 GA.
  sdk/docs/iot/README.md
Labels: Docs, EngSys, Iot, auto-merge

#1399 Update readme to use 'beta' instead of 'preview'
  README.md
Labels: Docs, auto-merge

#1398 update api string to latest
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/tests/iot/hub/test_az_iot_hub_client.c
Labels: Iot

#1400 Update other pnp sample to use native APIs
  sdk/samples/iot/CMakeLists.txt
  sdk/samples/iot/README.md
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_pnp_sample.c
Labels: Iot

#1402 Replace 'VSCode' with 'Visual Studio Code' in readme.md
  README.md
Labels: Docs, auto-merge

#1404 Fix bounds check while processing JSON string to avoid out-of-range access.
  sdk/src/azure/core/az_json_reader.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core, auto-merge

#1405 Simplify should-retry logic
  sdk/src/azure/core/az_http_policy_retry.c
Labels: Azure.Core

#1408 Update sample files to use universal headers
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_device_info_component.h
  sdk/samples/iot/pnp/pnp_mqtt_message.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
Labels: Client, Iot

#1407 Update the changelog for the 1.1.0 beta 1 release and add date.
  CHANGELOG.md
Labels: auto-merge

#1409 1.0.0 => 1.1.0-beta.1
  cmake-modules/AddAzureSDKforC.cmake
Labels: auto-merge

#1413 Reorder headers
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_mqtt_message.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
Labels: Client, Iot

#1414 Increment version for C SDK releases
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#1403 Sync eng/common directory with azure-sdk-tools for PR 1052
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Add-Issue-Comment.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/modules/ChangeLog-Operations.psm1
  eng/common/scripts/modules/Package-Properties.psm1
Labels: Central-EngSys, EngSys

#1381 Update documentation from JS comments
  eng/pipelines/templates/steps/vcpkg.yml
  sdk/docs/iot/README.md
  sdk/docs/iot/coding_patterns.md
  sdk/docs/iot/hub.md
  sdk/docs/iot/provisioning.md
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Client, Docs, Iot

#1417 Sync eng/common directory with azure-sdk-tools for PR 1066
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1416 Sync eng/common directory with azure-sdk-tools for PR 1077
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#1419 Readme edits
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Client, Docs, Iot

#1420 Sync eng/common directory with azure-sdk-tools for PR 1083
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#1361 Add helper comment in clang format validation step to let contributor know how to fix it
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: Client, EngSys, auto-merge

#1423 Sync eng/common directory with azure-sdk-tools for PR 1081
  eng/common/README.md
  eng/common/scripts/Add-Issue-Comment.ps1
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1426 Sync eng/common directory with azure-sdk-tools for PR 1088
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1425 Update Plug and Play find version API
  sdk/inc/azure/iot/az_iot_pnp_client.h
  sdk/samples/iot/paho_iot_pnp_component_sample.c
  sdk/samples/iot/paho_iot_pnp_sample.c
  sdk/src/azure/iot/az_iot_pnp_client_property.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_property.c
Labels: Iot

#1428 Remove duplicate phrases in README
  README.md
Labels: customer-reported

#1429 Update Plug and Play API doxygen
  sdk/inc/azure/iot/az_iot_pnp_client.h
Labels: Iot

#1433 Fix anchor tags to all lower cases
  README.md
Labels: Central-EngSys, EngSys

#1430 Sync eng/common directory with azure-sdk-tools for PR 1062
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys, auto-merge

#1432 Sync eng/common directory with azure-sdk-tools for PR 1091
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/add-pullrequest-reviewers.ps1
Labels: Central-EngSys, EngSys

#1435 Sync eng/common directory with azure-sdk-tools for PR 1103
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1436 Sync eng/common directory with azure-sdk-tools for PR 1019
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: Central-EngSys, EngSys

#1437 Sync eng/common directory with azure-sdk-tools for PR 1106
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1438 Sync eng/common directory with azure-sdk-tools for PR 968
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1439 Sync eng/common directory with azure-sdk-tools for PR 1102
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#1440 Sync eng/common directory with azure-sdk-tools for PR 1128
  eng/common/scripts/modules/ChangeLog-Operations.psm1
Labels: Central-EngSys, EngSys

#1443 Sync eng/common directory with azure-sdk-tools for PR 1104
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#1444 Sync eng/common directory with azure-sdk-tools for PR 1129
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#1442 Adding benchmark chart to readme
  sdk/docs/iot/README.md
Labels: Iot

#1446 Sync eng/common directory with azure-sdk-tools for PR 1132
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#1447 Sync eng/common directory with azure-sdk-tools for PR 1133
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#1445 Sync eng/common directory with azure-sdk-tools for PR 1127
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#1448 Sync eng/common directory with azure-sdk-tools for PR 1131
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: Central-EngSys, EngSys

#1450 Sync eng/common directory with azure-sdk-tools for PR 1109
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#1454 Sync eng/common directory with azure-sdk-tools for PR 1136
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#1453 Sync eng/common directory with azure-sdk-tools for PR 1135
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#1456 Sync eng/common directory with azure-sdk-tools for PR 1130
  eng/common/README.md
Labels: Central-EngSys, EngSys

#1455 Sync eng/common directory with azure-sdk-tools for PR 1137
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-az-modules.yml
Labels: Central-EngSys, EngSys

#1459 Update formatting on esp2866 how-to guide
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
Labels: Client, Docs, Iot

#1462 Update PnP language in sample readme
  sdk/samples/iot/README.md
Labels: Docs, Iot

#1463 Sync eng/common directory with azure-sdk-tools for PR 1144
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#1465 Sync eng/common directory with azure-sdk-tools for PR 1146
  eng/common/TestResources/Remove-TestResources.ps1
Labels: Central-EngSys, EngSys

#1466 Sync eng/common directory with azure-sdk-tools for PR 1148
  eng/common/README.md
Labels: Central-EngSys, EngSys

#1468 Sync eng/common directory with azure-sdk-tools for PR 1158
  eng/common/pipelines/templates/steps/verify-path-length.yml
Labels: Central-EngSys, EngSys

#1469 Sync eng/common directory with azure-sdk-tools for PR 1154
  eng/common/scripts/git-branch-push.ps1
  eng/common/scripts/modules/ChangeLog-Operations.psm1
Labels: Central-EngSys, EngSys
