Repository Azure/azure-sdk-for-c, pull requests merged in 2020-11, with the labels that each got.

#1470 Sync eng/common directory with azure-sdk-tools for PR 1160
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#1475 Sync eng/common directory with azure-sdk-tools for PR 1167
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#1480 Sync eng/common directory with azure-sdk-tools for PR 1175
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#1479 Patch up PnP branch rebase
  sdk/docs/iot/README.md
  sdk/samples/iot/CMakeLists.txt
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
  sdk/tests/iot/pnp/CMakeLists.txt
  sdk/tests/iot/pnp/test_az_iot_pnp_client_property.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_sas.c
Labels: Iot

#1477 simplify sample to make command work
  sdk/samples/iot/paho_iot_pnp_component_sample.c
Labels: Iot

#1484 Update changelog for beta 2
  CHANGELOG.md
Labels: Docs

#1485 Merge master into pnp feature branch
  CHANGELOG.md
  eng/common/TestResources/New-TestResources.ps1
Labels: Iot

#1483 Sync eng/common directory with azure-sdk-tools for PR 1163
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#1487 Sync eng/common directory with azure-sdk-tools for PR 1178
  eng/common/README.md
Labels: Central-EngSys, EngSys

#1486 patch the changelog for pnp feature branch
  CHANGELOG.md
Labels: Docs

#1489 Sync eng/common directory with azure-sdk-tools for PR 1185
  eng/common/README.md
Labels: Central-EngSys, EngSys

#1493 remove links which break validation for now
  sdk/samples/iot/README.md
Labels: auto-merge

#1497 Update semver validation regex to be more flexible and allow the prerelease label to contain a "feature." string
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys

#1500 Revert "Update semver validation regex to be more flexible and allow the prerelease label to contain a "feature." string"
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys

#1502 Sync eng/common directory with azure-sdk-tools for PR 1188
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#1503 Sync eng/common directory with azure-sdk-tools for PR 1190
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#1501 Update CHANGELOG.md
  CHANGELOG.md
Labels: EngSys

#1504 Update feature pnp changelog and version header to follow same versioning pattern
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: EngSys

#1481 Sync eng/common directory with azure-sdk-tools for PR 1170
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: Central-EngSys, EngSys

#1505 Reorganization of samples readme
  sdk/samples/iot/README.md
Labels: Client, Docs, Iot

#1508 Completion of Sample Readme update
  sdk/samples/iot/README.md
Labels: Client, Docs, Iot

#1474 Sync eng/common directory with azure-sdk-tools for PR 1161
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#1509 Sync eng/common directory with azure-sdk-tools for PR 1199
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#1510 Sync eng/common directory with azure-sdk-tools for PR 1202
  eng/common/TestResources/New-TestResources.ps1
Labels: Central-EngSys, EngSys

#1513 Sync eng/common directory with azure-sdk-tools for PR 1153
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#1495 Update AddAzureSDKforC.cmake to reference the latest tagged release of the SDK
  cmake-modules/AddAzureSDKforC.cmake
Labels: EngSys

#1506 Incrementing master CL and version to be above the next release from the feature branch
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: EngSys, auto-merge

#1511 PnP API Update - az_iot_pnp_client_property_get_next_component_property
  sdk/inc/azure/iot/az_iot_pnp_client.h
  sdk/samples/iot/paho_iot_pnp_component_sample.c
  sdk/samples/iot/paho_iot_pnp_sample.c
  sdk/samples/iot/paho_iot_pnp_with_provisioning_sample.c
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/src/azure/iot/az_iot_pnp_client_property.c
  sdk/tests/iot/pnp/test_az_iot_pnp_client_property.c
Labels: Iot

#1518 Update LanguageSetting.ps1
  eng/scripts/Language-Settings.ps1
Labels: EngSys

#1520 Merge master into feature/iot_pnp
  CHANGELOG.md
  cmake-modules/AddAzureSDKforC.cmake
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/SemVer.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
  eng/scripts/Language-Settings.ps1
  sdk/inc/azure/core/az_version.h
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_esp8266_nodemcu.md
  sdk/src/azure/core/az_context.c
  sdk/src/azure/core/az_http_policy_logging.c
  sdk/src/azure/core/az_http_request.c
  sdk/src/azure/core/az_http_response.c
  sdk/src/azure/core/az_json_reader.c
  sdk/src/azure/core/az_json_token.c
  sdk/src/azure/core/az_json_writer.c
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/src/azure/iot/az_iot_hub_client_c2d.c
  sdk/src/azure/iot/az_iot_hub_client_methods.c
  sdk/src/azure/iot/az_iot_hub_client_sas.c
  sdk/src/azure/iot/az_iot_hub_client_telemetry.c
  sdk/src/azure/iot/az_iot_hub_client_twin.c
  sdk/src/azure/iot/az_iot_provisioning_client.c
  sdk/src/azure/iot/az_iot_provisioning_client_sas.c
  sdk/src/azure/platform/az_curl.c
  sdk/src/azure/platform/az_nohttp.c
Labels: Iot

#1521 clean up iot sample readme to sync with master
  sdk/samples/iot/README.md
Labels: Iot

#1515 Sync eng/common directory with azure-sdk-tools for PR 1210
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#1522 Make sure we still have a beta.2 version within the changelog in the main branch, corresponding to what got released
  CHANGELOG.md
Labels: EngSys

#1523 Fix PnP Changelog
  CHANGELOG.md
Labels: Docs, Iot, auto-merge

#1525 Sync eng/common directory with azure-sdk-tools for PR 1203
  eng/common/scripts/Add-IssueComment.ps1
  eng/common/scripts/Add-IssueLabels.ps1
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Get-PullRequestCreator.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Submit-PullRequest.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
  eng/common/scripts/create-tags-and-git-release.ps1
  eng/common/scripts/update-docs-ci.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#1526 Sync eng/common directory with azure-sdk-tools for PR 1222
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#1527 Sync eng/common directory with azure-sdk-tools for PR 1219
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/assets/logo.svg
  eng/common/docgeneration/docfx.json
  eng/common/docgeneration/templates/matthews/partials/affix.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.header.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/class.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/enum.tmpl.partial
  eng/common/docgeneration/templates/matthews/partials/namespace.tmpl.partial
  eng/common/docgeneration/templates/matthews/styles/main.css
  eng/common/docgeneration/templates/matthews/styles/main.js
  eng/common/pipelines/templates/steps/docindex.yml
Labels: Central-EngSys, EngSys

#1529 Sync eng/common directory with azure-sdk-tools for PR 1226
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/docindex.yml
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#1530 Sync eng/common directory with azure-sdk-tools for PR 1229
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#1528 Sync eng/common directory with azure-sdk-tools for PR 1220
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: Central-EngSys, EngSys

#1531 Clean up / Ignore unnecessary CI artifacts, Issue #1422
  .gitignore
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys, customer-reported
