Repository Azure/azure-sdk-for-c, pull requests merged in 2021-03, with the labels that each got.

#1617 Add azure-sdk-for-c IoT sample for Espressif ESP32
  sdk/docs/iot/README.md
  sdk/samples/iot/README.md
  sdk/samples/iot/aziot_esp32/AzIoTSasToken.cpp
  sdk/samples/iot/aziot_esp32/AzIoTSasToken.h
  sdk/samples/iot/aziot_esp32/New-ArduinoZipLibrary.ps1
  sdk/samples/iot/aziot_esp32/New-TrustedCertHeader.ps1
  sdk/samples/iot/aziot_esp32/SerialLogger.cpp
  sdk/samples/iot/aziot_esp32/SerialLogger.h
  sdk/samples/iot/aziot_esp32/aziot_esp32.ino
  sdk/samples/iot/aziot_esp32/create_trusted_cert_header.sh
  sdk/samples/iot/aziot_esp32/generate_arduino_zip_library.sh
  sdk/samples/iot/aziot_esp32/iot_configs.h
  sdk/samples/iot/docs/how_to_iot_hub_esp32.md
Labels: Iot

#1621 update methods precondition to greater than 0
  sdk/src/azure/iot/az_iot_hub_client_methods.c
Labels: Iot

#1629 Sync eng/common directory with azure-sdk-tools for PR 1456
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#1631 Sync eng/common directory with azure-sdk-tools for PR 1459
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#1633 Sync eng/common directory with azure-sdk-tools for PR 1467
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#1632 Sync eng/common directory with azure-sdk-tools for PR 1465
  eng/common/pipelines/templates/steps/create-apireview.yml
Labels: Central-EngSys, EngSys

#1630 Sync eng/common directory with azure-sdk-tools for PR 1448
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#1634 Sync eng/common directory with azure-sdk-tools for PR 1461
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, EngSys

#1636 Sync eng/common directory with azure-sdk-tools for PR 1470
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: Central-EngSys, EngSys

#1637 Sync eng/common directory with azure-sdk-tools for PR 1472
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: Central-EngSys, EngSys

#1638 Sync eng/common directory with azure-sdk-tools for PR 1452
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, EngSys

#1644 Sync eng/common directory with azure-sdk-tools for PR 1479
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/SemVer.ps1
Labels: Central-EngSys, EngSys

#1640 update precondition on provisioning to minimum size 1
  CHANGELOG.md
  sdk/src/azure/iot/az_iot_provisioning_client.c
Labels: Iot

#1645 Sync eng/common directory with azure-sdk-tools for PR 1485
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: Central-EngSys, EngSys

#1646 add error checking for iot live test scripts
  sdk/samples/iot/templates/iothub/test-resources-post.ps1
Labels: Iot

#1642 Sync eng/common directory with azure-sdk-tools for PR 1458
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#1647 Sync eng/common directory with azure-sdk-tools for PR 1490
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: Central-EngSys, EngSys

#1626 Sync eng/common directory with azure-sdk-tools for PR 1418
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#1650 Sync eng/common directory with azure-sdk-tools for PR 1496
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#1651 Sync eng/common directory with azure-sdk-tools for PR 1463
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, EngSys

#1652 Sync eng/common directory with azure-sdk-tools for PR 1498
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, EngSys

#1653 Sync eng/common directory with azure-sdk-tools for PR 1489
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#1657 Sync eng/common directory with azure-sdk-tools for PR 1502
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#1661 Sync eng/common directory with azure-sdk-tools for PR 1476
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#1656 generate map files for iot samples
  cmake-modules/create_map_file.cmake
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  sdk/samples/iot/CMakeLists.txt
  sdk/tests/core/CMakeLists.txt
  sdk/tests/iot/common/CMakeLists.txt
  sdk/tests/iot/hub/CMakeLists.txt
  sdk/tests/iot/provisioning/CMakeLists.txt
Labels: Iot

#1663 Sync eng/common directory with azure-sdk-tools for PR 1514
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: Central-EngSys, EngSys

#1664 Sync eng/common directory with azure-sdk-tools for PR 1517
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#1665 Sync eng/common directory with azure-sdk-tools for PR 1478
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/scripts/Invoke-GitHubAPI.ps1
  eng/common/scripts/Submit-PullRequest.ps1
Labels: Central-EngSys, EngSys

#1660 Sync eng/common directory with azure-sdk-tools for PR 1508
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#1666 Sync eng/common directory with azure-sdk-tools for PR 1493
  eng/common/pipelines/templates/steps/publish-blobs.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1668 Sync eng/common directory with azure-sdk-tools for PR 1521
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
Labels: Central-EngSys, EngSys

#1667 Sync eng/common directory with azure-sdk-tools for PR 1477
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/git-push-changes.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#1671 Sync eng/common directory with azure-sdk-tools for PR 1527
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#1670 Update readme around vcpkg
  README.md
Labels: Docs
