Repository Azure/azure-sdk-for-c, pull requests merged in 2021-07, with the labels that each got.

#1810 Sync eng/common directory with azure-sdk-tools for PR 1768
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: Central-EngSys, EngSys

#1812 Sync eng/common directory with azure-sdk-tools for PR 1772
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#1802 Add public current depth field to JSON reader.
  CHANGELOG.md
  sdk/inc/azure/core/az_json.h
  sdk/src/azure/core/az_json_reader.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core

#1809 Update codeowners file
  .github/CODEOWNERS
Labels: EngSys

#1814 Sync eng/common directory with azure-sdk-tools for PR 1782
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#1813 Sync eng/common directory with azure-sdk-tools for PR 1767
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/deploy-test-resources.yml
Labels: Central-EngSys, EngSys

#1816 Add base64 encoding and decoding APIs that accept az_span.
  CHANGELOG.md
  sdk/inc/azure/az_core.h
  sdk/inc/azure/core/az_base64.h
  sdk/src/azure/core/CMakeLists.txt
  sdk/src/azure/core/az_base64.c
  sdk/tests/core/CMakeLists.txt
  sdk/tests/core/az_test_definitions.h
  sdk/tests/core/main.c
  sdk/tests/core/test_az_base64.c
Labels: Azure.Core

#1820 Fix link substitution
  eng/scripts/Language-Settings.ps1
Labels: EngSys

#1823 Sync eng/common directory with azure-sdk-tools for PR 1780
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#1822 Add back the GitHub Codespaces section to samples/iot/README.md.
  sdk/samples/iot/README.md
Labels: Docs, IoT

#1824 Update the changelog to introduce the IoT Plug and Play feature and samples
  CHANGELOG.md
Labels: IoT

#1828 Sync eng/common directory with azure-sdk-tools for PR 1808
  eng/common/scripts/FilterPoliCheckResults.ps1
Labels: Central-EngSys, EngSys

#1803 Sync eng/common directory with azure-sdk-tools for PR 1748
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#1827 Increment version for C SDK releases and add date to main
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: EngSys

#1842 Sync eng/common directory with azure-sdk-tools for PR 1827
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#1844 Sync eng/common directory with azure-sdk-tools for PR 1848
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/docgeneration/templates/matthews/partials/head.tmpl.partial
Labels: Central-EngSys, EngSys

#1845 Sync eng/common directory with azure-sdk-tools for PR 1847
  eng/common/scripts/Create-APIReview.ps1
Labels: Central-EngSys, EngSys

#1846 Sync eng/common directory with azure-sdk-tools for PR 1851
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: Central-EngSys, EngSys

#1848 Add GA to individual docs and doc index
  eng/docs/api/assets/header.html
  eng/scripts/Language-Settings.ps1
Labels: Central-EngSys
