Repository Azure/azure-sdk-for-c, pull requests merged in 2021-02, with the labels that each got.

#1582 Sync eng/common directory with azure-sdk-tools for PR 1351
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#1583 Sync eng/common directory with azure-sdk-tools for PR 1361
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#1584 Sync eng/common directory with azure-sdk-tools for PR 1353
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#1585 Sync eng/common directory with azure-sdk-tools for PR 1364
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#1586 Sync eng/common directory with azure-sdk-tools for PR 1365
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
Labels: Central-EngSys, EngSys

#1587 Sync eng/common directory with azure-sdk-tools for PR 1366
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: Central-EngSys, EngSys

#1589 Sync eng/common directory with azure-sdk-tools for PR 1376
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/SemVer.ps1
Labels: Central-EngSys, EngSys

#1593 Sync eng/common directory with azure-sdk-tools for PR 1393
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: Central-EngSys, EngSys

#1595 Sync eng/common directory with azure-sdk-tools for PR 1303
  eng/common/scripts/Collect-ChangeLogs.ps1
Labels: Central-EngSys, EngSys

#1580 wrap CMP0091 in MSVC check
  CMakeLists.txt
  eng/cmake/global_compile_options.txt
Labels: Azure.Core

#1596 Sync eng/common directory with azure-sdk-tools for PR 1358
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#1592 Update CMakeLists.txt
  sdk/src/azure/core/CMakeLists.txt
Labels: customer-reported

#1598 Sync eng/common directory with azure-sdk-tools for PR 1386
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#1599 Sync eng/common directory with azure-sdk-tools for PR 1307
  eng/common/scripts/Update-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#1601 Sync eng/common directory with azure-sdk-tools for PR 1401
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#1603 Sync eng/common directory with azure-sdk-tools for PR 1405
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#1600 Make sure az_json_writer_append_json_text appends a comma between elements of an array.
  CHANGELOG.md
  sdk/src/azure/core/az_json_writer.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core

#1604 update doc on mqtt topic parsing
  sdk/inc/azure/iot/az_iot_hub_client.h
Labels: Iot

#1606 Sync eng/common directory with azure-sdk-tools for PR 1408
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/README.md
Labels: Central-EngSys, EngSys

#1590 Sync eng/common directory with azure-sdk-tools for PR 1371
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys

#1588 Re-enable agent OS verification
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/pipelines/templates/stages/archetype-c-release.yml
Labels: Central-EngSys, EngSys

#1607 Sync eng/common directory with azure-sdk-tools for PR 1374
  eng/common/pipelines/templates/steps/create-apireview.yml
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#1611 Sync eng/common directory with azure-sdk-tools for PR 1396
  eng/common/docgeneration/templates/matthews/styles/main.js
Labels: Central-EngSys, EngSys

#1609 Sync eng/common directory with azure-sdk-tools for PR 1415
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
Labels: Central-EngSys, EngSys

#1612 Sync eng/common directory with azure-sdk-tools for PR 1425
  eng/common/scripts/get-markdown-files-from-changed-files.ps1
Labels: Central-EngSys, EngSys

#1613 Sync eng/common directory with azure-sdk-tools for PR 1429
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/samples/matrix-job-sample.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
  eng/common/scripts/job-matrix/tests/test-import-matrix.json
Labels: Central-EngSys, EngSys

#1615 Sync eng/common directory with azure-sdk-tools for PR 1436
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#1614 Sync eng/common directory with azure-sdk-tools for PR 1428
  eng/common/pipelines/templates/steps/verify-agent-os.yml
  eng/common/scripts/Verify-AgentOS.ps1
Labels: Central-EngSys, EngSys

#1616 Sync eng/common directory with azure-sdk-tools for PR 1421
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: Central-EngSys, EngSys

#1619 add precondition documentation to iot apis
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
Labels: Iot

#1622 Sync eng/common directory with azure-sdk-tools for PR 1447
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/common.ps1
  eng/common/scripts/logging.ps1
Labels: Central-EngSys, EngSys
