Repository Azure/azure-sdk-for-c, pull requests merged in 2021-11, with the labels that each got.

#1967 Sync eng/common directory with azure-sdk-tools for PR 2177
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#1969 Sync eng/common directory with azure-sdk-tools for PR 2203
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#1971 Sync eng/common directory with azure-sdk-tools for PR 2179
  eng/common/pipelines/templates/steps/docker-pull-image.yml
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1970 Update changelog
  CHANGELOG.md
Labels: Azure.Core

#1968 HTTP request telemetry improvements
  CHANGELOG.md
  sdk/inc/azure/core/internal/az_http_internal.h
  sdk/src/azure/core/az_http_policy.c
  sdk/tests/core/test_az_policy.c
Labels: Azure.Core

#1938 add links to middleware | update TOC
  README.md
Labels: Docs

#1896 Update codespace launch.json
  .vscode-config/codespaces-launch.json
Labels: IoT

#1973 Sync eng/common directory with azure-sdk-tools for PR 2053
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#1975 Late PR feedback follow-up
  CHANGELOG.md
  sdk/inc/azure/core/az_http.h
  sdk/src/azure/core/az_http_policy.c
Labels: Azure.Core

#1974 Sync eng/common directory with azure-sdk-tools for PR 2199
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1972 add callout for json writer space needed
  sdk/inc/azure/core/az_json.h
Labels: Azure.Core

#1976 Telemetry options constructor and component name size constraint
  sdk/inc/azure/core/internal/az_http_internal.h
  sdk/src/azure/core/az_http_policy.c
  sdk/tests/core/test_az_policy.c
Labels: Azure.Core

#1977 Sync eng/common directory with azure-sdk-tools for PR 2202
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#1960 Storage Blobs API
  .github/CODEOWNERS
  CHANGELOG.md
  CMakeLists.txt
  CONTRIBUTING.md
  README.md
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  samples/README.md
  sdk/docs/storage/README.md
  sdk/inc/azure/storage/az_storage_blobs.h
  sdk/samples/storage/blobs/CMakeLists.txt
  sdk/samples/storage/blobs/README.md
  sdk/samples/storage/blobs/src/blobs_client_sample.c
  sdk/samples/storage/blobs/test-resources-post.ps1
  sdk/samples/storage/blobs/test-resources.json
  sdk/src/azure/storage/CMakeLists.txt
  sdk/src/azure/storage/az_storage_blobs_blob_client.c
  sdk/tests/storage/blobs/CMakeLists.txt
  sdk/tests/storage/blobs/_az_test_http_client.c
  sdk/tests/storage/blobs/_az_test_http_client.h
  sdk/tests/storage/blobs/main.c
  sdk/tests/storage/blobs/test_az_storage_blobs.c
Labels: Storage

#1985 Sync eng/common directory with azure-sdk-tools for PR 2219
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-docker.yml
Labels: EngSys, Central-EngSys

#1986 Sync eng/common directory with azure-sdk-tools for PR 2223
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#1987 Remove duplicate LICENSE file
  sdk/docs/core/LICENSE
Labels: Azure.Core

#1988 Update repo link (master => main)
  sdk/samples/iot/README.md
Labels: Docs

#1989 Remove `en-us` from microsoft links, and fix a couple of dead links
  sdk/inc/azure/core/internal/az_precondition_internal.h
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_hub_client_properties.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
  sdk/src/azure/iot/az_iot_provisioning_client.c
Labels: Docs, IoT

#1995 `main` => `feature/storage-blobs`
  CHANGELOG.md
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-docker.yml
  sdk/docs/core/LICENSE
  sdk/inc/azure/core/internal/az_precondition_internal.h
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_hub_client_properties.h
  sdk/inc/azure/iot/az_iot_provisioning_client.h
  sdk/samples/iot/README.md
  sdk/src/azure/iot/az_iot_provisioning_client.c
Labels: Storage

#1994 Sync eng/common directory with azure-sdk-tools for PR 2240
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#1996 Sync eng/common directory with azure-sdk-tools for PR 2242
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1997 Make live tests to build Storage samples with Curl transport
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
Labels: Storage

#1999 Update links to point to a feature branch
  README.md
  samples/README.md
  sdk/docs/storage/README.md
  sdk/samples/storage/blobs/README.md
Labels: Docs, Storage

#2003 Increment version for C SDK releases in main
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#1983 Update doc comment for json writer's requirement of slack space and add to other APIs that need it.
  sdk/inc/azure/core/az_json.h
Labels: Docs, Azure.Core

#2005 Sync eng/common directory with azure-sdk-tools for PR 2249
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#1924 add VxWorks samples and related README
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_vxworks.md
  sdk/samples/iot/docs/img/after_provision.png
  sdk/samples/iot/docs/img/before_provision.png
  sdk/samples/iot/docs/img/device_twin.png
  sdk/samples/iot/docs/img/device_twin_doc.png
  sdk/samples/iot/vxworks/azureClientSample.c
  sdk/samples/iot/vxworks/azureProvisioningClientSample.c
Labels: customer-reported, IoT

#2008 Sync eng/common directory with azure-sdk-tools for PR 2247
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/clouds/AzureChinaCloud.json
  eng/common/TestResources/clouds/AzureCloud.json
  eng/common/TestResources/clouds/AzureUSGovernment.json
Labels: EngSys, Central-EngSys

#2010 Fix order of arguments for _az_http_policy_apiversion_options
  sdk/inc/azure/core/internal/az_http_internal.h
Labels: Azure.Core

#2009 Sync eng/common directory with azure-sdk-tools for PR 2259
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2011 Sync eng/common directory with azure-sdk-tools for PR 2265
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#2006 Fixing OpenSSL cert generation.
  .devcontainer/post_build.sh
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
  sdk/samples/iot/templates/iothub/test-resources-post.ps1
  sdk/samples/iot/x509_config.cfg
Labels: IoT, EngSys

#2013 Sync eng/common directory with azure-sdk-tools for PR 2276
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: EngSys, Central-EngSys

#2015 Sync eng/common directory with azure-sdk-tools for PR 2267
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#2016 Sync eng/common directory with azure-sdk-tools for PR 2272
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#2017 Sync eng/common directory with azure-sdk-tools for PR 2290
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2023 Sync eng/common directory with azure-sdk-tools for PR 2321
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2024 Sync eng/common directory with azure-sdk-tools for PR 2306
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#2025 Sync eng/common directory with azure-sdk-tools for PR 2322
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#2026 Sync eng/common directory with azure-sdk-tools for PR 2333
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#2028 Sync eng/common directory with azure-sdk-tools for PR 2086
  eng/common/pipelines/templates/steps/get-pr-owners.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#2030 Sync eng/common directory with azure-sdk-tools for PR 2348
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#2027 fix custom iot user agent
  CHANGELOG.md
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/tests/iot/hub/test_az_iot_hub_client.c
Labels: IoT

#2029 Sync eng/common directory with azure-sdk-tools for PR 2331
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
