Repository Azure/azure-sdk-for-c, pull requests merged in 2021-09, with the labels that each got.

#1889 Sync eng/common directory with azure-sdk-tools for PR 1967
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: EngSys, Central-EngSys

#1890 Sync eng/common directory with azure-sdk-tools for PR 1972
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#1891 Merge feature/iot_pnp branch into main
  CHANGELOG.md
  sdk/docs/iot/README.md
  sdk/inc/azure/az_iot.h
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/inc/azure/iot/az_iot_hub_client_properties.h
  sdk/samples/iot/CMakeLists.txt
  sdk/samples/iot/README.md
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
  sdk/samples/iot/paho_iot_pnp_component_sample.c
  sdk/samples/iot/paho_iot_pnp_sample.c
  sdk/samples/iot/paho_iot_pnp_sample_common.c
  sdk/samples/iot/paho_iot_pnp_sample_common.h
  sdk/samples/iot/paho_iot_pnp_with_provisioning_sample.c
  sdk/samples/iot/pnp/pnp_device_info_component.c
  sdk/samples/iot/pnp/pnp_device_info_component.h
  sdk/samples/iot/pnp/pnp_mqtt_message.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  sdk/samples/iot/pnp/pnp_protocol.c
  sdk/samples/iot/pnp/pnp_protocol.h
  sdk/samples/iot/pnp/pnp_temperature_controller_component.c
  sdk/samples/iot/pnp/pnp_temperature_controller_component.h
  sdk/samples/iot/pnp/pnp_thermostat_component.c
  sdk/samples/iot/pnp/pnp_thermostat_component.h
  sdk/src/azure/iot/CMakeLists.txt
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/src/azure/iot/az_iot_hub_client_commands.c
  sdk/src/azure/iot/az_iot_hub_client_properties.c
  sdk/tests/iot/hub/CMakeLists.txt
  sdk/tests/iot/hub/main.c
  sdk/tests/iot/hub/test_az_iot_hub_client.h
  sdk/tests/iot/hub/test_az_iot_hub_client_commands.c
  sdk/tests/iot/hub/test_az_iot_hub_client_methods.c
  sdk/tests/iot/hub/test_az_iot_hub_client_properties.c
Labels: IoT

#1902 Update dependency types to linux
  cgmanifest.json
Labels: EngSys

#1903 Sync eng/common directory with azure-sdk-tools for PR 1986
  eng/common/testproxy/docker-start-proxy.ps1
Labels: EngSys, Central-EngSys

#1901 Update uses of internal current depth field from Json Reader to use the public one.
  sdk/src/azure/iot/az_iot_hub_client_properties.c
Labels: IoT

#1904 Convert cfgmanifest linux entries to matching format
  cgmanifest.json
Labels: EngSys

#1899 Update changelog to release 1.2.0 with IoT Plug and Play
  CHANGELOG.md
  cmake-modules/AddAzureSDKforC.cmake
  sdk/inc/azure/core/az_version.h
Labels: EngSys

#1906 Sync eng/common directory with azure-sdk-tools for PR 1982
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
Labels: EngSys, Central-EngSys

#1905 az_json_writer_append_json_text does not take into account required buffer space for commas
  sdk/src/azure/core/az_json_writer.c
Labels: customer-reported

#1907 Add unit test to make sure internal state of json writer is set correctly.
  sdk/tests/core/test_az_json.c
Labels: Azure.Core, test-enhancement

#1909 Update the changelog to include a recent bug fix by community member.
  CHANGELOG.md
Labels: Docs

#1914 Fix up the changelog year for 1.2.0 to be 2021 instead of 2017
  CHANGELOG.md
Labels: Docs

#1915 Increment version for C SDK releases
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#1916 Sync eng/common directory with azure-sdk-tools for PR 1977
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1910 Sync eng/common directory with azure-sdk-tools for PR 1995
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1917 Sync eng/common directory with azure-sdk-tools for PR 1983
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
Labels: EngSys, Central-EngSys

#1919 Sync eng/common directory with azure-sdk-tools for PR 1946
  eng/common/scripts/check-spelling-in-changed-files.ps1
Labels: EngSys, Central-EngSys

#1921 Sync eng/common directory with azure-sdk-tools for PR 2006
  eng/common/scripts/SemVer.ps1
Labels: EngSys, Central-EngSys

#1922 Sync eng/common directory with azure-sdk-tools for PR 1979
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1925 Sync eng/common directory with azure-sdk-tools for PR 2008
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1923 Sync eng/common directory with azure-sdk-tools for PR 2009
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
Labels: EngSys, Central-EngSys

#1927 Sync eng/common directory with azure-sdk-tools for PR 2016
  eng/common/pipelines/templates/steps/verify-changelog.yml
Labels: EngSys, Central-EngSys

#1926 Sync eng/common directory with azure-sdk-tools for PR 2011
  eng/common/pipelines/templates/steps/detect-api-changes.yml
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#1929 Sync eng/common directory with azure-sdk-tools for PR 2010
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1931 Sync eng/common directory with azure-sdk-tools for PR 2025
  eng/common/scripts/Collect-ChangeLogs.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: EngSys, Central-EngSys

#1934 Sync eng/common directory with azure-sdk-tools for PR 2035
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#1936 Sync eng/common directory with azure-sdk-tools for PR 2031
  eng/common/pipelines/templates/steps/policheck.yml
Labels: EngSys, Central-EngSys

#1932 Sync eng/common directory with azure-sdk-tools for PR 2027
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1935 Sync eng/common directory with azure-sdk-tools for PR 2039
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
Labels: EngSys, Central-EngSys

#1942 make iot sample common buffers static
  sdk/samples/iot/iot_sample_common.c
  sdk/samples/iot/iot_sample_common.h
Labels: IoT

#1941 Sync eng/common directory with azure-sdk-tools for PR 2046
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys
