Repository Azure/azure-sdk-for-c, pull requests merged in 2021-06, with the labels that each got.

#1766 Sync eng/common directory with azure-sdk-tools for PR 1611
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: Central-EngSys, EngSys

#1770 Fix for Issue #1768
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/src/azure/iot/az_iot_hub_client_twin.c
Labels: Client, Iot, bug

#1774 Sync eng/common directory with azure-sdk-tools for PR 1658
  eng/common/scripts/Delete-RemoteBranches.ps1
Labels: Central-EngSys, EngSys

#1771 Sync eng/common directory with azure-sdk-tools for PR 1645
  eng/common/scripts/git-branch-push.ps1
Labels: Central-EngSys, EngSys

#1776 Sync eng/common directory with azure-sdk-tools for PR 1654
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#1778 Sync eng/common directory with azure-sdk-tools for PR 1633
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#1779 Sync eng/common directory with azure-sdk-tools for PR 1685
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Update-ChangeLog.ps1
  eng/common/scripts/Verify-ChangeLog.ps1
Labels: Central-EngSys, EngSys

#1780 Fix of depricated BearSSL method call of WiFiClientSecure class in sample for ESP8266.
  sdk/samples/iot/aziot_esp8266/aziot_esp8266.ino
Labels: customer-reported

#1782 Sync eng/common directory with azure-sdk-tools for PR 1688
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#1783 Update for master -> main branch rename
  sdk/ci.yml
Labels: Central-EngSys

#1788 Sync eng/common directory with azure-sdk-tools for PR 1711
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#1790 Sync eng/common directory with azure-sdk-tools for PR 1716
  eng/common/README.md
  eng/common/docgeneration/Generate-DocIndex.ps1
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/eng-common-workflow-enforcer.yml
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/artifact-metadata-parsing.ps1
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: Central-EngSys, EngSys

#1793 Sync eng/common directory with azure-sdk-tools for PR 1719
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: Central-EngSys, EngSys

#1794 Sync eng/common directory with azure-sdk-tools for PR 1729
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Save-Package-Properties.ps1
Labels: Central-EngSys, EngSys

#1795 Sync eng/common directory with azure-sdk-tools for PR 1736
  eng/common/pipelines/templates/steps/bypass-local-dns.yml
Labels: Central-EngSys, EngSys

#1799 Sync eng/common directory with azure-sdk-tools for PR 1739
  eng/common/scripts/Verify-Links.ps1
  eng/common/scripts/update-docs-metadata.ps1
Labels: Central-EngSys, EngSys

#1805 Sync eng/common directory with azure-sdk-tools for PR 1725
  eng/common/pipelines/templates/steps/enable-long-path-support.yml
  eng/common/pipelines/templates/steps/set-daily-docs-branch-name.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Invoke-DevOpsAPI.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Queue-Pipeline.ps1
  eng/common/scripts/Save-Package-Properties.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#1806 Sync eng/common directory with azure-sdk-tools for PR 1759
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
Labels: Central-EngSys, EngSys

#1807 Sync eng/common directory with azure-sdk-tools for PR 1763
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys
