Repository Azure/azure-sdk-for-c, pull requests merged in 2021-05, with the labels that each got.

#1724 Sync eng/common directory with azure-sdk-tools for PR 1579
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#1728 Sync eng/common directory with azure-sdk-tools for PR 1524
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#1730 Merge master branch into feature/iot_cbor
  .devcontainer/devcontainer.json
  .devcontainer/post_build.sh
  .gitignore
  .vscode-config/codespaces-launch.json
  .vscode-config/codespaces-tasks.json
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/pipelines/templates/steps/set-default-branch.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/ChangeLog-Operations.ps1
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Package-Properties.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
  eng/common/scripts/Verify-Links.ps1
  eng/pipelines/templates/stages/archetype-c-release.yml
  eng/pipelines/templates/steps/vcpkg.yml
  sdk/samples/iot/README.md
  sdk/samples/iot/aziot_esp32/readme.md
  sdk/samples/iot/aziot_esp8266/readme.md
  sdk/samples/iot/aziot_realtek_amebaD/readme.md
  sdk/samples/iot/docs/img/codespace.png
Labels: Docs, Iot, feature-request

#1731 Update samples to include log of mqtt client username
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_component_sample.c
  sdk/samples/iot/paho_iot_hub_pnp_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
Labels: Iot

#1738 Typo "Github"→"GitHub"
  sdk/samples/iot/aziot_esp8266/readme.md
Labels: customer-reported

#1740 Sync eng/common directory with azure-sdk-tools for PR 1596
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#1746 Sync eng/common directory with azure-sdk-tools for PR 1597
  eng/common/scripts/Prepare-Release.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys

#1747 Sync eng/common directory with azure-sdk-tools for PR 1594
  eng/common/pipelines/templates/steps/create-pull-request.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#1752 Fix sample readme urls
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Docs, Iot

#1754 Sync eng/common directory with azure-sdk-tools for PR 1598
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
Labels: Central-EngSys, EngSys

#1758 Sync eng/common directory with azure-sdk-tools for PR 1585
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#1761 Sync eng/common directory with azure-sdk-tools for PR 1615
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/pipelines/docindex.yml
Labels: Central-EngSys, EngSys

#1755 add clang format version
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys

#1763 Sync eng/common directory with azure-sdk-tools for PR 1627
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#1764 Sync eng/common directory with azure-sdk-tools for PR 1629
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: Central-EngSys, EngSys

#1767 Sync eng/common directory with azure-sdk-tools for PR 1635
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: Central-EngSys, EngSys

#1769 Sync eng/common directory with azure-sdk-tools for PR 1606
  eng/common/TestResources/AzurePowerShellV4/Utility.ps1
  eng/common/TestResources/Import-AzModules.ps1
  eng/common/TestResources/deploy-test-resources.yml
  eng/common/TestResources/remove-test-resources.yml
  eng/common/TestResources/setup-environments.yml
  eng/common/pipelines/templates/steps/cache-ps-modules.yml
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/Import-AzModules.ps1
Labels: Central-EngSys, EngSys
