Repository Azure/azure-sdk-for-c, pull requests merged in 2021-04, with the labels that each got.

#1674 Sync eng/common directory with azure-sdk-tools for PR 1525
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/README.md
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/Update-TestResources.cmd
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1.md
Labels: Central-EngSys, EngSys

#1675 Sync eng/common directory with azure-sdk-tools for PR 1535
  eng/common/pipelines/templates/jobs/archetype-sdk-tests-generate.yml
  eng/common/scripts/job-matrix/samples/matrix-test.yml
Labels: Central-EngSys, EngSys

#1681 Sync eng/common directory with azure-sdk-tools for PR 1546
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys, EngSys

#1682 Sync eng/common directory with azure-sdk-tools for PR 1548
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: Central-EngSys, EngSys

#1680 Sync eng/common directory with azure-sdk-tools for PR 1515
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: Central-EngSys, EngSys

#1684 Sync eng/common directory with azure-sdk-tools for PR 1534
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
  eng/common/scripts/update-docs-ci.ps1
Labels: Central-EngSys, EngSys

#1686 Sync eng/common directory with azure-sdk-tools for PR 1551
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#1687 Sync eng/common directory with azure-sdk-tools for PR 1504
  eng/common/pipelines/templates/steps/daily-dev-build-variable.yml
Labels: Central-EngSys, EngSys

#1683 Enable retain runs.
  eng/pipelines/templates/stages/archetype-c-release.yml
Labels: Central-EngSys, EngSys

#1688 Sync eng/common directory with azure-sdk-tools for PR 1553
  eng/common/pipelines/templates/steps/retain-run.yml
Labels: Central-EngSys, EngSys

#1689 Revert retain.
  eng/pipelines/templates/stages/archetype-c-release.yml
Labels: Central-EngSys, EngSys

#1691 Sync eng/common directory with azure-sdk-tools for PR 1552
  eng/common/pipelines/templates/steps/docs-metadata-release.yml
Labels: Central-EngSys, EngSys

#1692 Add Code of Conduct file
  CODE_OF_CONDUCT.md
Labels: Docs

#1693 Sync eng/common directory with azure-sdk-tools for PR 1557
  eng/common/pipelines/templates/steps/verify-agent-os.yml
Labels: Central-EngSys, EngSys

#1695 Sync eng/common directory with azure-sdk-tools for PR 1555
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: Central-EngSys, EngSys

#1696 Sync eng/common directory with azure-sdk-tools for PR 1559
  eng/common/pipelines/templates/steps/verify-samples.yml
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: Central-EngSys, EngSys

#1699 add test for too many written properties
  CHANGELOG.md
  sdk/src/azure/iot/az_iot_common.c
  sdk/tests/iot/common/test_az_iot_common.c
Labels: Iot

#1702 CBOR documentation
  NOTICE.txt
  cgmanifest.json
  sdk/samples/iot/README.md
Labels: Docs, Iot, feature-request

#1701 Sync eng/common directory with azure-sdk-tools for PR 1560
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys, EngSys

#1706 Sync eng/common directory with azure-sdk-tools for PR 1563
  eng/common/TestResources/build-test-resource-config.yml
Labels: Central-EngSys, EngSys

#1705 Update vcpkg instructions for subdirectory readmes
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Docs, Iot

#1704 CBOR sample docs update
  cgmanifest.json
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_linux.md
  sdk/samples/iot/docs/how_to_iot_hub_samples_windows.md
Labels: Docs, Iot, feature-request

#1709 Sync eng/common directory with azure-sdk-tools for PR 1564
  eng/common/scripts/Package-Properties.ps1
Labels: Central-EngSys, EngSys

#1710 Sync eng/common directory with azure-sdk-tools for PR 1558
  eng/common/pipelines/templates/steps/set-default-branch.yml
Labels: Central-EngSys, EngSys

#1708 Sync eng/common directory with azure-sdk-tools for PR 1565
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
Labels: Central-EngSys, EngSys

#1703 CBOR Twin code implementation
  sdk/inc/azure/iot/az_iot_hub_client.h
  sdk/src/azure/iot/az_iot_hub_client.c
  sdk/tests/iot/hub/test_az_iot_hub_client.c
Labels: Iot, feature-request

#1717 Sync eng/common directory with azure-sdk-tools for PR 1562
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#1714 Enable retain runs.
  eng/pipelines/templates/stages/archetype-c-release.yml
Labels: Central-EngSys, EngSys

#1718 CBOR: Remove check line in sample README
  sdk/samples/iot/README.md
Labels: Docs, Iot, feature-request

#1623 Adding comment for vcpkg triplet in the unique key for caching
  eng/pipelines/templates/steps/vcpkg.yml
Labels: EngSys, auto-merge, customer-reported

#1721 Sync eng/common directory with azure-sdk-tools for PR 1580
  eng/common/scripts/Verify-Links.ps1
Labels: Central-EngSys, EngSys

#1723 update directions on monitoring telemetry data
  sdk/samples/iot/aziot_esp32/readme.md
  sdk/samples/iot/aziot_esp8266/readme.md
  sdk/samples/iot/aziot_realtek_amebaD/readme.md
Labels: Iot

#1725 Sync eng/common directory with azure-sdk-tools for PR 1572
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: Central-EngSys, EngSys

#1722 Sync eng/common directory with azure-sdk-tools for PR 1577
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: Central-EngSys, EngSys

#1726 add codespace support
  .devcontainer/devcontainer.json
  .devcontainer/post_build.sh
  .gitignore
  .vscode-config/codespaces-launch.json
  .vscode-config/codespaces-tasks.json
  sdk/samples/iot/README.md
  sdk/samples/iot/docs/img/codespace.png
Labels: Iot

#1727 Sync eng/common directory with azure-sdk-tools for PR 1584
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Update-DevOps-Release-WorkItem.ps1
Labels: Central-EngSys, EngSys
