Repository Azure/azure-sdk-for-c, pull requests merged in 2021-12, with the labels that each got.

#2022 Sync eng/common directory with azure-sdk-tools for PR 2248
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/build-test-resource-config.yml
Labels: EngSys, Central-EngSys

#2031 Sync eng/common directory with azure-sdk-tools for PR 2352
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/scripts/check-spelling-in-changed-files.ps1
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#2033 Sync eng/common directory with azure-sdk-tools for PR 2372
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2034 Sync eng/common directory with azure-sdk-tools for PR 2380
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#2038 Sync eng/common directory with azure-sdk-tools for PR 2327
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#2040 Sync eng/common directory with azure-sdk-tools for PR 2381
  eng/common/pipelines/templates/steps/write-filesystemmetrics.yml
  eng/common/scripts/Write-FileSystemMetrics.ps1
Labels: EngSys, Central-EngSys

#2039 Sync eng/common directory with azure-sdk-tools for PR 2363
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2041 Sync eng/common directory with azure-sdk-tools for PR 2393
  eng/common/scripts/Update-DocsMsPackages.ps1
Labels: EngSys, Central-EngSys

#2042 Sync eng/common directory with azure-sdk-tools for PR 2402
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#2043 Sync eng/common directory with azure-sdk-tools for PR 2408
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2044 Sync eng/common directory with azure-sdk-tools for PR 2412
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2046 Sync eng/common directory with azure-sdk-tools for PR 2415
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2047 Sync eng/common directory with azure-sdk-tools for PR 2417
  eng/common/pipelines/templates/steps/verify-readme.yml
  eng/common/scripts/Verify-Readme.ps1
Labels: EngSys, Central-EngSys

#2050 add String call to other rc
  sdk/samples/iot/aziot_esp32/AzIoTSasToken.cpp
Labels: IoT

#2051 Sync eng/common directory with azure-sdk-tools for PR 2442
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#2053 Sync eng/common directory with azure-sdk-tools for PR 2447
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2055 Add trademark section to readme
  README.md
Labels: auto-merge

#1885 Fix compilation error C4576 with C++ and MSVC 2019 (19.28.29913)
  sdk/inc/azure/core/az_json.h
Labels: customer-reported
