Repository Azure/azure-sdk-for-c, pull requests merged in 2022-07, with the labels that each got.

#2252 Sync eng/common directory with azure-sdk-tools for PR 3563
  eng/common/pipelines/templates/steps/verify-samples.yml
Labels: EngSys, Central-EngSys

#2253 Sync eng/common directory with azure-sdk-tools for PR 3428
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#2254 Sync eng/common directory with azure-sdk-tools for PR 3577
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#2257 Sync eng/common directory with azure-sdk-tools for PR 3568
  eng/common/scripts/Verify-Resource-Ref.ps1
Labels: EngSys, Central-EngSys

#2255 Sync eng/common directory with azure-sdk-tools for PR 3500
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2258 Sync eng/common directory with azure-sdk-tools for PR 3480
  eng/common/pipelines/templates/steps/validate-filename.yml
Labels: EngSys, Central-EngSys

#2261 Use consistent service directory for remove test resources step
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
Labels: Central-EngSys

#2262 Sync eng/common directory with azure-sdk-tools for PR 3546
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#2263 Sync eng/common directory with azure-sdk-tools for PR 3590
  eng/common/pipelines/templates/steps/set-test-pipeline-version.yml
  eng/common/scripts/SetTestPipelineVersion.ps1
Labels: EngSys, Central-EngSys

#2266 Sync eng/common directory with azure-sdk-tools for PR 3606
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#2267 Sync eng/common directory with azure-sdk-tools for PR 3584
  eng/common/pipelines/templates/jobs/docindex.yml
Labels: EngSys, Central-EngSys

#2268 Sync eng/common directory with azure-sdk-tools for PR 3578
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#2271 Sync eng/common directory with azure-sdk-tools for PR 3642
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#2273 Sync eng/common directory with azure-sdk-tools for PR 3657
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#2274 Sync eng/common directory with azure-sdk-tools for PR 3656
  eng/common/testproxy/test-proxy-docker.yml
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2260 Increment version for C SDK releases
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#2270 Sync eng/common directory with azure-sdk-tools for PR 3628
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2277 Sync eng/common directory with azure-sdk-tools for PR 3700
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#2278 Sync eng/common directory with azure-sdk-tools for PR 3702
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#2276 Fix-up version increment after the 1.3.2 GA release
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#2281 Sync eng/common directory with azure-sdk-tools for PR 3661
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#2280 Sync eng/common directory with azure-sdk-tools for PR 3735
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2285 Sync eng/common directory with azure-sdk-tools for PR 3754
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys

#2289 Sync eng/common directory with azure-sdk-tools for PR 3753
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#2290 Unescape
  sdk/inc/azure/core/az_json.h
  sdk/src/azure/core/az_json_token.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core

#2292 Sync eng/common directory with azure-sdk-tools for PR 3787
  eng/common/TestResources/setup-environments.yml
Labels: EngSys, Central-EngSys
