Repository Azure/azure-sdk-for-c, pull requests merged in 2022-08, with the labels that each got.

#2293 Sync eng/common directory with azure-sdk-tools for PR 3765
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys

#2296 Sync eng/common directory with azure-sdk-tools for PR 3826
  eng/common/pipelines/templates/steps/verify-links.yml
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2291 Remove unreachable condition in az_json_token as it's redundant
  sdk/src/azure/core/az_json_token.c
Labels: Azure.Core

#2297 Add null manifest scenario
  sdk/src/azure/iot/az_iot_adu_client.c
  sdk/tests/iot/adu/test_az_iot_adu.c
Labels: IoT

#2300 Sync eng/common directory with azure-sdk-tools for PR 3860
  eng/common/testproxy/dotnet-devcert.crt
  eng/common/testproxy/dotnet-devcert.pfx
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2305 update links to iot docs
  sdk/docs/iot/README.md
Labels: Docs

#2306 use new all inclusive headers in docs
  README.md
  sdk/docs/iot/coding_patterns.md
Labels: Docs

#2303 Add null terminator for char* based json string unescape, and precondition on input length
  sdk/inc/azure/core/az_json.h
  sdk/src/azure/core/az_json_token.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core

#2307 Update change log for main for August release, to release 1.4.0-beta.1
  CHANGELOG.md
Labels: Docs

#2311 Increment version for C SDK releases
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#2304 Fix version incrementing after GA release
  eng/scripts/SdkVersion-Common.ps1
  eng/scripts/Update-SdkVersion.ps1
  eng/scripts/tests/Update-SdkVersion.constants.ps1
  eng/scripts/tests/Update-SdkVersion.tests.ps1
Labels: EngSys

#2316 Sync eng/common directory with azure-sdk-tools for PR 3945
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2321 Sync eng/common directory with azure-sdk-tools for PR 3874
  eng/common/pipelines/templates/jobs/perf.yml
  eng/common/pipelines/templates/steps/sparse-checkout.yml
Labels: EngSys, Central-EngSys
