Repository Azure/azure-sdk-for-c, pull requests merged in 2022-01, with the labels that each got.

#2057 Sync eng/common directory with azure-sdk-tools for PR 2464
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2059 Sync eng/common directory with azure-sdk-tools for PR 2484
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2045 Sync eng/common directory with azure-sdk-tools for PR 2416
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2061 Sync eng/common directory with azure-sdk-tools for PR 2500
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#2060 Sync eng/common directory with azure-sdk-tools for PR 2513
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2062 Storage: remove the condition that is already verified by preconditions
  sdk/src/azure/storage/az_storage_blobs_blob_client.c
Labels: Storage

#2052 Improve Storage code coverage
  sdk/tests/storage/blobs/main.c
  sdk/tests/storage/blobs/test_az_storage_blobs.c
Labels: Storage, MQ

#2066 Sync eng/common directory with azure-sdk-tools for PR 2554
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2067 Sync eng/common directory with azure-sdk-tools for PR 2545
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#2071 Sync eng/common directory with azure-sdk-tools for PR 2592
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2070 Sync eng/common directory with azure-sdk-tools for PR 2585
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2073 Sync eng/common directory with azure-sdk-tools for PR 2596
  eng/common/pipelines/templates/steps/retain-run.yml
  eng/common/scripts/Add-RetentionLease.ps1
  eng/common/scripts/Invoke-DevOpsAPI.ps1
Labels: EngSys, Central-EngSys

#2074 Sync eng/common directory with azure-sdk-tools for PR 2578
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2076 Sync eng/common directory with azure-sdk-tools for PR 2581
  eng/common/scripts/Get-AADIdentityFromGithubUser.ps1
Labels: EngSys, Central-EngSys

#2075 Sync eng/common directory with azure-sdk-tools for PR 2599
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2078 Sync eng/common directory with azure-sdk-tools for PR 2604
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: EngSys, Central-EngSys

#2081 Sync eng/common directory with azure-sdk-tools for PR 2617
  eng/common/pipelines/templates/steps/verify-links.yml
Labels: EngSys, Central-EngSys

#2083 Sync eng/common directory with azure-sdk-tools for PR 2641
  eng/common/scripts/job-matrix/README.md
Labels: EngSys, Central-EngSys
