Repository Azure/azure-sdk-for-c, pull requests merged in 2022-11, with the labels that each got.

#2380 Sync eng/common directory with azure-sdk-tools for PR 4544
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2379 Sync eng/common directory with azure-sdk-tools for PR 4574
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2384 Sync eng/common directory with azure-sdk-tools for PR 4591
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#2383 Sync eng/common directory with azure-sdk-tools for PR 4586
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#2387 Sync eng/common directory with azure-sdk-tools for PR 4603
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#2390 Sync eng/common directory with azure-sdk-tools for PR 4606
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2394 Sync eng/common directory with azure-sdk-tools for PR 4622
  eng/common/TestResources/clouds/AzureCloud.json
Labels: EngSys, Central-EngSys

#2396 Sync eng/common directory with azure-sdk-tools for PR 4629
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2400 Update vcpkg baseline to the October 2022 tag.
  cmake-modules/AzureVcpkg.cmake
  eng/vcpkg-commit.txt
  sdk/samples/iot/paho_iot_hub_c2d_sample.c
  sdk/samples/iot/paho_iot_hub_methods_sample.c
  sdk/samples/iot/paho_iot_hub_sas_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_telemetry_sample.c
  sdk/samples/iot/paho_iot_hub_twin_sample.c
  sdk/samples/iot/paho_iot_pnp_sample.c
  sdk/samples/iot/paho_iot_pnp_sample_common.c
  sdk/samples/iot/paho_iot_pnp_with_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sample.c
  sdk/samples/iot/paho_iot_provisioning_sas_sample.c
  sdk/samples/iot/pnp/pnp_mqtt_message.h
  vcpkg.json
Labels: EngSys

#2411 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#2414 pr feedback
  sdk/inc/azure/iot/internal/az_iot_adu_internal.h
  sdk/src/azure/iot/CMakeLists.txt
Labels: IoT

#2412 Update az_json_string_unescape to accept az_span as destination to improve usability of API.
  CHANGELOG.md
  sdk/inc/azure/core/az_json.h
  sdk/src/azure/core/az_json_token.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core

#2417 Sync eng/common directory with azure-sdk-tools for PR 4666
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2418 Sync eng/common directory with azure-sdk-tools for PR 4631
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2421 update docs for no delta updates
  sdk/inc/azure/iot/az_iot_adu_client.h
Labels: Docs, IoT

#2415 Update change log for main for November release, to release 1.4.0, with version update.
  CHANGELOG.md
  cmake-modules/AddAzureSDKforC.cmake
  sdk/inc/azure/core/az_version.h
Labels: EngSys

#2375 Add Azure Device Update code to main
  CMakeLists.txt
  sdk/docs/iot/README.md
  sdk/inc/azure/az_iot.h
  sdk/inc/azure/core/az_span.h
  sdk/inc/azure/iot/az_iot_adu_client.h
  sdk/inc/azure/iot/az_iot_common.h
  sdk/inc/azure/iot/internal/az_iot_adu_internal.h
  sdk/samples/iot/README.md
  sdk/src/azure/iot/CMakeLists.txt
  sdk/src/azure/iot/az_iot_adu_client.c
  sdk/src/azure/iot/az_iot_hub_client_properties.c
  sdk/tests/iot/adu/CMakeLists.txt
  sdk/tests/iot/adu/main.c
  sdk/tests/iot/adu/test_az_iot_adu.c
  sdk/tests/iot/adu/test_az_iot_adu.h
  sdk/tests/iot/hub/test_az_iot_hub_client_properties.c
Labels: IoT

#2423 Update changelog to include the upgrade of dependencies baseline from vcpkg
  CHANGELOG.md
Labels: EngSys

#2424 ADU Changelog
  CHANGELOG.md
Labels: Docs, IoT

#2425 Increment version for C SDK releases
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: auto-merge

#2426 Sync eng/common directory with azure-sdk-tools for PR 4687
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2427 Sync eng/common directory with azure-sdk-tools for PR 4632
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#2428 Sync eng/common directory with azure-sdk-tools for PR 4701
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#2429 Sync eng/common directory with azure-sdk-tools for PR 4726
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2420 Sync eng/common directory with azure-sdk-tools for PR 4628
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#2430 Sync eng/common directory with azure-sdk-tools for PR 4728
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#2431 Sync eng/common directory with azure-sdk-tools for PR 4746
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#2434 Sync eng/common directory with azure-sdk-tools for PR 4713
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys
