Repository Azure/azure-sdk-for-c, pull requests merged in 2022-10, with the labels that each got.

#2355 Sync eng/common directory with azure-sdk-tools for PR 4315
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2356 Sync eng/common directory with azure-sdk-tools for PR 4311
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#2359 Add default .assets directory to .gitignore
  .gitignore
Labels: Central-EngSys

#2357 Sync eng/common directory with azure-sdk-tools for PR 4341
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2361 Sync eng/common directory with azure-sdk-tools for PR 4372
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#2366 Sync eng/common directory with azure-sdk-tools for PR 3790
  eng/common/scripts/Helpers/PSModule-Helpers.ps1
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2367 Sync eng/common directory with azure-sdk-tools for PR 4486
  eng/common/spelling/Invoke-Cspell.ps1
  eng/common/spelling/package-lock.json
  eng/common/spelling/package.json
Labels: EngSys, Central-EngSys

#2368 Sync eng/common directory with azure-sdk-tools for PR 4480
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#2369 Sync eng/common directory with azure-sdk-tools for PR 4504
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2370 Sync eng/common directory with azure-sdk-tools for PR 4527
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2372 Fix minimum log buffer size calculation
  CHANGELOG.md
  sdk/src/azure/core/az_http_policy_logging.c
  sdk/tests/core/test_az_logging.c
Labels: Azure.Core

#2376 Sync eng/common directory with azure-sdk-tools for PR 4543
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#2377 Fix zlib 1.2.12 vcpkg failure
  vcpkg.json
Labels: Azure.Core

#2373 Sync eng/common directory with azure-sdk-tools for PR 4532
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys
