Repository Azure/azure-sdk-for-c, pull requests merged in 2022-02, with the labels that each got.

#2089 Sync eng/common directory with azure-sdk-tools for PR 2608
  eng/common/pipelines/templates/steps/update-docsms-metadata.yml
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2088 Sync eng/common directory with azure-sdk-tools for PR 2605
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2091 Sync eng/common directory with azure-sdk-tools for PR 2673
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2090 Sync eng/common directory with azure-sdk-tools for PR 2668
  eng/common/scripts/artifact-metadata-parsing.ps1
Labels: EngSys, Central-EngSys

#2096 Sync eng/common directory with azure-sdk-tools for PR 2682
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#2097 Sync eng/common directory with azure-sdk-tools for PR 2685
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2095 Update azureClientSample.c
  sdk/samples/iot/vxworks/azureClientSample.c
Labels: customer-reported

#2098 Sync eng/common directory with azure-sdk-tools for PR 2691
  eng/common/scripts/Helpers/DevOps-WorkItem-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#2100 Sync eng/common directory with azure-sdk-tools for PR 2686
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2086 Fix broken GitHub links in Contributing.md
  CONTRIBUTING.md
Labels: Docs

#2101 Sync eng/common directory with azure-sdk-tools for PR 2720
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#2102 Add total bytes written public field to the JSON writer, by moving it from internal.
  sdk/inc/azure/core/az_json.h
  sdk/src/azure/core/az_json_writer.c
  sdk/tests/core/test_az_json.c
Labels: Azure.Core

#2087 Update change log for main for February release, to release 1.3.0, with version update
  CHANGELOG.md
  cmake-modules/AddAzureSDKforC.cmake
  sdk/inc/azure/core/az_version.h
Labels: Docs

#2099 Sync eng/common directory with azure-sdk-tools for PR 2679
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Update-TestResources.ps1
Labels: EngSys, Central-EngSys

#2105 Sync eng/common directory with azure-sdk-tools for PR 2721
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2106 Sync eng/common directory with azure-sdk-tools for PR 2733
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2107 remove localization on links
  sdk/inc/azure/iot/az_iot_common.h
Labels: Docs, IoT

#2109 Sync eng/common directory with azure-sdk-tools for PR 2739
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2110 Sync eng/common directory with azure-sdk-tools for PR 2740
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2115 Sync eng/common directory with azure-sdk-tools for PR 2754
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2111 Sync eng/common directory with azure-sdk-tools for PR 2741
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2114 Sync eng/common directory with azure-sdk-tools for PR 2758
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2117 Sync eng/common directory with azure-sdk-tools for PR 2759
  eng/common/scripts/Update-DocsMsToc.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#2119 Sync eng/common directory with azure-sdk-tools for PR 2775
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2120 Sync eng/common directory with azure-sdk-tools for PR 2768
  eng/common/scripts/Verify-Links.ps1
Labels: EngSys, Central-EngSys

#2123 Sync eng/common directory with azure-sdk-tools for PR 2805
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#2124 Sync eng/common directory with azure-sdk-tools for PR 2808
  eng/common/scripts/Detect-Api-Changes.ps1
Labels: EngSys, Central-EngSys

#2126 Sync eng/common directory with azure-sdk-tools for PR 2771
  eng/common/scripts/copy-from-blobstorage.ps1
Labels: EngSys, Central-EngSys
