Repository Azure/azure-sdk-for-c, pull requests merged in 2022-04, with the labels that each got.

#2166 Sync eng/common directory with azure-sdk-tools for PR 2967
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/job-matrix/job-matrix-functions.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#2167 Sync eng/common directory with azure-sdk-tools for PR 2966
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2168 Update CHANGELOG per PR 2162.
  CHANGELOG.md
Labels: Docs, IoT

#2171 Manually increment version for C SDK releases to 1.4.0-beta.1
  CHANGELOG.md
  sdk/inc/azure/core/az_version.h
Labels: Docs

#2176 Sync eng/common directory with azure-sdk-tools for PR 3092
  eng/common/testproxy/test-proxy-tool.yml
Labels: EngSys, Central-EngSys

#2175 Sync eng/common directory with azure-sdk-tools for PR 3067
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/Remove-TestResources.ps1.md
  eng/common/TestResources/SubConfig-Helpers.ps1
  eng/common/TestResources/Update-TestResources.ps1
  eng/common/TestResources/remove-test-resources.yml
Labels: EngSys, Central-EngSys

#2179 Sync eng/common directory with azure-sdk-tools for PR 2963
  eng/common/scripts/ChangeLog-Operations.ps1
Labels: EngSys, Central-EngSys

#2181 Sync eng/common directory with azure-sdk-tools for PR 2942
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#2183 Sync eng/common directory with azure-sdk-tools for PR 3123
  eng/common/pipelines/templates/steps/credscan.yml
Labels: EngSys, Central-EngSys

#2182 Sync eng/common directory with azure-sdk-tools for PR 3124
  eng/common/TestResources/Remove-TestResources.ps1
  eng/common/TestResources/SubConfig-Helpers.ps1
Labels: EngSys, Central-EngSys

#2163 Sync eng/common directory with azure-sdk-tools for PR 3000
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: EngSys, Central-EngSys

#2185 Sync eng/common directory with azure-sdk-tools for PR 3145
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#2186 Sync eng/common directory with azure-sdk-tools for PR 3153
  eng/common/TestResources/New-TestResources.ps1
  eng/common/TestResources/New-TestResources.ps1.md
  eng/common/TestResources/deploy-test-resources.yml
Labels: EngSys, Central-EngSys

#2191 Sync eng/common directory with azure-sdk-tools for PR 3160
  eng/common/docgeneration/Generate-DocIndex.ps1
Labels: EngSys, Central-EngSys

#2192 Sync eng/common directory with azure-sdk-tools for PR 3169
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2193 Sync eng/common directory with azure-sdk-tools for PR 3188
  eng/common/pipelines/templates/steps/publish-blobs.yml
Labels: EngSys, Central-EngSys

#2195 Sync eng/common directory with azure-sdk-tools for PR 3212
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2196 Sync eng/common directory with azure-sdk-tools for PR 3238
  eng/common/testproxy/docker-start-proxy.ps1
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#2197 Sync eng/common directory with azure-sdk-tools for PR 3221
  eng/common/scripts/Update-DocsMsMetadata.ps1
Labels: EngSys, Central-EngSys

#2198 Sync eng/common directory with azure-sdk-tools for PR 3061
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys

#2199 Sync eng/common directory with azure-sdk-tools for PR 3250
  eng/common/scripts/Delete-RemoteBranches.ps1
  eng/common/scripts/Invoke-GitHubAPI.ps1
Labels: EngSys, Central-EngSys
